language: c

env:
 global:
  - EnableNuGetPackageRestore=true 

before_install:
 - sudo add-apt-repository ppa:directhex/monoxide -y && sudo apt-get update
 - mozroots --import --sync
 
install:
 - sudo apt-get install mono-devel mono-gmcs nunit-console
 
script:
 - xbuild CI.proj
 - nunit-console ./NUnitTests/bin/Debug/NUnitTests.dll
