language: c

env:
 global:
  - EnableNuGetPackageRestore=true 

install:
 - sudo add-apt-repository ppa:directhex/monoxide -y && sudo apt-get update
 - sudo apt-get install mono-devel mono-gmcs nunit-console
 - mozroots --import --sync
 - mono .nuget/NuGet.exe restore Picagari.sln
 
script:
 - xbuild CI.proj
 - nunit-console ./Picagari/Tests/bin/Debug/Picagari.Tests.dll
